/**
 * @fileoverview Mock implementations for PrimeReact components used in tests
 * @description Enterprise-grade test mocks for PrimeReact UI components
 * @author Generated by AI Assistant
 * @version 1.0.0
 * @license AGPL-3.0-only
 */

import React from 'react';

// Filter function to remove non-standard HTML props
const filterHTMLProps = (props: Record<string, any>) => {
  const {
    rounded, severity, outlined, size, text, raised, icon, iconPos,
    inputStyle, showButtons, minFractionDigits, maxFractionDigits,
    locale, useGrouping, prefix, suffix, currency, currencyDisplay,
    onValueChange, // PrimeReact specific event handler
    ...htmlProps
  } = props;
  return htmlProps;
};

// Mock Button component
export const Button: React.FC<any> = (props) => {
  const { label, children, ...htmlProps } = filterHTMLProps(props);
  return (
    <button {...htmlProps}>
      {label || children}
    </button>
  );
};

// Mock InputNumber component
export const InputNumber: React.FC<any> = (props) => {
  const { value, onChange, ...htmlProps } = filterHTMLProps(props);
  
  // Handle controlled vs uncontrolled input
  const inputProps = {
    ...htmlProps,
    type: "number",
    ...(value !== undefined ? { value } : {}),
    ...(onChange ? { onChange } : { readOnly: true })
  };
  
  return (
    <div>
      <input {...inputProps} />
    </div>
  );
};

// Mock Slider component
export const Slider: React.FC<any> = (props) => {
  const htmlProps = filterHTMLProps(props);
  return (
    <div>
      <input
        type="range"
        {...htmlProps}
      />
    </div>
  );
};

// Mock Dialog component
export const Dialog: React.FC<any> = (props) => {
  const { visible, children, header, ...htmlProps } = filterHTMLProps(props);
  if (!visible) return null;
  
  return (
    <div data-testid="dialog" {...htmlProps}>
      {header && <h2>{header}</h2>}
      {children}
    </div>
  );
};

// Mock ProgressBar component
export const ProgressBar: React.FC<any> = (props) => {
  const { value, color, ...htmlProps } = filterHTMLProps(props);
  return (
    <div 
      data-testid="progress-bar" 
      {...htmlProps}
      style={{ 
        ...htmlProps.style, 
        backgroundColor: color || '#e5e5e5',
        width: '100%',
        height: '20px'
      }}
    >
      <div 
        style={{ 
          width: `${value || 0}%`, 
          height: '100%', 
          backgroundColor: color || '#0ea5e9' 
        }}
      />
    </div>
  );
};